# Generated by Django 3.0.3 on 2020-07-25 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_notificationforstudent_slug'),
        ('teacher', '0002_notifiacationsforteacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifiacationsforteacher',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Teacher'),
        ),
    ]
