# Generated by Django 3.0.3 on 2020-07-17 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='s_class',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
