# Generated by Django 3.0.3 on 2020-07-26 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_notificationforstudent_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotificationForStudent',
        ),
    ]
