# Generated by Django 3.0.3 on 2020-08-18 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_delete_notificationforstudent'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='updated',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='updated',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='s_contact',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='s_gender',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='t_contact',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='t_gender',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
