# Generated by Django 3.0.3 on 2020-07-09 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='question',
            field=models.TextField(max_length=300, null=True),
        ),
    ]
