# Generated by Django 3.0.3 on 2020-07-26 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_delete_notificationforstudent'),
        ('student', '0004_notificationforstudent'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationforstudent',
            name='notyfy_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Class'),
        ),
    ]
