# Generated by Django 3.0.3 on 2020-07-09 05:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('ass_class', models.CharField(max_length=30)),
                ('topic', models.CharField(max_length=30, null=True)),
                ('last_date', models.DateField(null=True)),
                ('ass_type', models.CharField(max_length=30)),
                ('slug', models.CharField(max_length=30, null=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MCQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('que', models.TextField(max_length=3000)),
                ('opt1', models.CharField(max_length=30)),
                ('opt2', models.CharField(max_length=30)),
                ('opt3', models.CharField(max_length=30)),
                ('opt4', models.CharField(max_length=30)),
                ('ans', models.CharField(max_length=30)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment.Assignment')),
            ],
        ),
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField(max_length=3000)),
                ('file', models.FileField(null=True, upload_to='assignment/files')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment.Assignment')),
            ],
        ),
    ]
