# Generated by Django 3.0.3 on 2020-07-17 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0002_remove_fileupload_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='ass_class',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
