# Generated by Django 3.0.3 on 2020-07-17 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0003_auto_20200717_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='slug',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
