# Generated by Django 3.0.3 on 2020-07-18 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0005_auto_20200717_2010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='topic',
        ),
        migrations.AddField(
            model_name='assignment',
            name='subject',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
