# Generated by Django 3.0.3 on 2020-07-18 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_subject'),
        ('assignment', '0006_auto_20200718_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Subject'),
        ),
    ]
